### ISSUE TITLE
Font Family Inconsistency: Figma Design vs. Application Implementation

### ISSUE THREAD

**Issue by SabIoana** [peviitor-ro/template-job-description-react#1]
ENVIRONMENT: DEVELOPMENT
url:  https://www.figma.com/file/3rF6YxXENPgw9xp6iYelxz/peviitor.ro?type=design&node-id=1- 
      51&mode=design&t=Ym5svvHPr6oHyRXG-0
url:  https://job-description-template-react.netlify.app//
browser: Chrome
devices: desktop, mobile

STEPS TO REPRODUCE:
   1. Open Figma and app url in browser
   2. Navigate to the template app url  and Figma url
   3. Compare the font family used in the template app with the design in Figma

EXPECTED RESULTS:
The font family used in the template app should match the "Roboto" font family specified in the Figma design.
Text across the application should consistently render in the "Roboto" font family.

ACTUAL RESULTS:
The font family used in the app is "Inter" instead of "Roboto", as per the Figma design

**Comment by talidag** [comment]
fixed the font family
