### ISSUE TITLE
Alignment and margin discrepancy in table list

### ISSUE THREAD

**Issue by SabIoana** [peviitor-ro/template-job-description-react#2]
ENVIRONMENT: DEVELOPMENT
url: https://www.figma.com/file/3rF6YxXENPgw9xp6iYelxz/peviitor.ro?type=design&node-id=1-
51&mode=design&t=Ym5svvHPr6oHyRXG-0
url: https://job-description-template-react.netlify.app//
browser: Chrome
devices: desktop, mobile

STEPS TO REPRODUCE:
   1. Open Figma and app url in browser
   2. Navigate to app url 
   3. Observe the margin and alignment of the text in the table entries

EXPECTED RESULTS:
The margin-left of the table entries should be consistent and aligned properly with the rest of the content.

ACTUAL RESULTS:
The margin-left of the table entries is not as expected; it appears to be misaligned.

![JobBody](https://github.com/peviitor-ro/template-job-description-react/assets/135150327/869d53d2-74ff-45fd-afad-4d511bb11295)

**Comment by talidag** [comment]
fixed the alignment issue
