### ISSUE TITLE
Missing "Apply" button in template app vs. Figma design

### ISSUE THREAD

**Issue by SabIoana** [peviitor-ro/template-job-description-react#3]
ENVIRONMENT: DEVELOPMENT
url: https://www.figma.com/file/3rF6YxXENPgw9xp6iYelxz/peviitor.ro?type=design&node-id=1-
      51&mode=design&t=Ym5svvHPr6oHyRXG-0
url: https://job-description-template-react.netlify.app//
browser: Chrome
devices: desktop, mobile

STEPS TO REPRODUCE:
    1. Open Figma and app url in browser
    2. Navigate to app url
    3. Verify that the "Aplica" button is displayed at the bottom of the template app

EXPECTED RESULTS:
The "Aplica" button should be visible within the template application, matching the design layout provided in Figma.

ACTUAL RESULTS:
The "Aplica" button is missing from the template app, deviating from the Figma design.

**Comment by talidag** [comment]
apply button added
