### ISSUE TITLE
Misaligned ''Apply'' button at bottom of page

### ISSUE THREAD

**Issue by SabIoana** [peviitor-ro/template-job-description-react#4]
ENVIRONMENT: DEVELOPMENT
url: https://www.figma.com/file/3rF6YxXENPgw9xp6iYelxz/peviitor.ro?type=design&node-id=1-
51&mode=design&t=Ym5svvHPr6oHyRXG-0
url: https://job-description-template-react.netlify.app//
browser: Chrome
devices: desktop, mobile

STEPS TO REPRODUCE:
   1. Open Figma and app url in browser
   2. Navigate to app url
   3. Check that the "Aplica" button at the bottom page is centered as Figma design

EXPECTED RESULTS:
The "Aplica" button, positioned at the bottom of the page, should maintain accurate center alignment both horizontally and vertically, in alignment with the design specifications.

ACTUAL RESULTS:
The "Aplica" button at the bottom of the page is misaligned with a leftward offset, deviating from the intended center alignment.

![apply button](https://github.com/peviitor-ro/template-job-description-react/assets/135150327/f3ef7d86-6cf1-403f-9910-317fc79ce92f)

**Comment by talidag** [comment]
fixed the apply button position
